spring:

  # Hateoas config
  hateoas:
    use-hal-as-default-json-media-type: false

  # Jackson config
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    time-zone: America/Sao_Paulo
    default-property-inclusion: non_null

  # Profiles config
  profiles:
    active: prod

  # SQL config
  jpa:
    properties:
      hibernate:
        format_sql: true

# Log config
logging:
  file:
    name: app.log
  logback:
    rollingpolicy:
      clean-history-on-start: true

# Actuator config
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

# API descriptions
info:
  app:
    name: ${project.name}
    description: <p>API RESTful feita para integração com o serviço de Webhook do GitHub — voltado apenas para issues.</p>
      <p>A API tem como objetivo receber, processar e armazenar as informações geradas ao abrir, modificar ou excluir uma issue.</p>
    version: ${project.version}

    contact:
      github: https://github.com/gabrielgoisandrade/
      name: Gabriel Gois Andrade
      email: gabriel.gois.andrade14@gmail.com

    license:
      url: https://www.apache.org/licenses/LICENSE-2.0.txt
      name: Apache License 2.0