spring:
  # Datasource config
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:webhook
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect