spring:
  # Jackson config
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    time-zone: UTC

    # Datasource config
  datasource:
    username: postgres
    password: 58326248
    url: jdbc:postgresql://localhost:5432/webhook
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      format_sql: true

  # Flyway config
  flyway:
    password: 58326248
    user: postgres
    url: jdbc:postgresql://localhost:5432/webhook
    schemas: public
    check-location: true
    baseline-on-migrate: true