package com.gga.webhook.utils

class PayloadUtils private constructor(){
    companion object{

        const val PAYLOAD_FULL: String = "{\n" +
                "    \"action\": \"closed\",\n" +
                "    \"issue\": {\n" +
                "      \"url\": \"https://api.github.com/repos/mock/webhook/issues/16\",\n" +
                "      \"repository_url\": \"https://api.github.com/repos/mock/webhook\",\n" +
                "      \"labels_url\": \"https://api.github.com/repos/mock/webhook/issues/16/labels{/name}\",\n" +
                "      \"comments_url\": \"https://api.github.com/repos/mock/webhook/issues/16/comments\",\n" +
                "      \"events_url\": \"https://api.github.com/repos/mock/webhook/issues/16/events\",\n" +
                "      \"html_url\": \"https://github.com/mock/webhook/issues/16\",\n" +
                "      \"id\": 809869512,\n" +
                "      \"node_id\": \"MDU6SXNzdWU4MDk4Njk1MTI=\",\n" +
                "      \"number\": 16,\n" +
                "      \"title\": \"titulo\",\n" +
                "      \"user\": {\n" +
                "        \"login\": \"mock\",\n" +
                "        \"id\": 42354016,\n" +
                "        \"node_id\": \"MDQ6VXNlcjQyMzU0MDE2\",\n" +
                "        \"avatar_url\": \"https://avatars.githubusercontent.com/u/42354016?v=4\",\n" +
                "        \"gravatar_id\": \"\",\n" +
                "        \"url\": \"https://api.github.com/users/mock\",\n" +
                "        \"html_url\": \"https://github.com/mock\",\n" +
                "        \"followers_url\": \"https://api.github.com/users/mock/followers\",\n" +
                "        \"following_url\": \"https://api.github.com/users/mock/following{/other_user}\",\n" +
                "        \"gists_url\": \"https://api.github.com/users/mock/gists{/gist_id}\",\n" +
                "        \"starred_url\": \"https://api.github.com/users/mock/starred{/owner}{/repo}\",\n" +
                "        \"subscriptions_url\": \"https://api.github.com/users/mock/subscriptions\",\n" +
                "        \"organizations_url\": \"https://api.github.com/users/mock/orgs\",\n" +
                "        \"repos_url\": \"https://api.github.com/users/mock/repos\",\n" +
                "        \"events_url\": \"https://api.github.com/users/mock/events{/privacy}\",\n" +
                "        \"received_events_url\": \"https://api.github.com/users/mock/received_events\",\n" +
                "        \"type\": \"User\",\n" +
                "        \"site_admin\": false\n" +
                "      },\n" +
                "      \"labels\": [\n" +
                "        {\n" +
                "          \"id\": 2584689276,\n" +
                "          \"node_id\": \"MDU6TGFiZWwyNTg0Njg5Mjc2\",\n" +
                "          \"url\": \"https://api.github.com/repos/mock/webhook/labels/bug\",\n" +
                "          \"name\": \"bug\",\n" +
                "          \"color\": \"d73a4a\",\n" +
                "          \"default\": true,\n" +
                "          \"description\": \"Something isn't working\"\n" +
                "        }\n" +
                "      ],\n" +
                "      \"state\": \"closed\",\n" +
                "      \"locked\": false,\n" +
                "      \"assignee\": {\n" +
                "        \"login\": \"mock\",\n" +
                "        \"id\": 42354016,\n" +
                "        \"node_id\": \"MDQ6VXNlcjQyMzU0MDE2\",\n" +
                "        \"avatar_url\": \"https://avatars.githubusercontent.com/u/42354016?v=4\",\n" +
                "        \"gravatar_id\": \"\",\n" +
                "        \"url\": \"https://api.github.com/users/mock\",\n" +
                "        \"html_url\": \"https://github.com/mock\",\n" +
                "        \"followers_url\": \"https://api.github.com/users/mock/followers\",\n" +
                "        \"following_url\": \"https://api.github.com/users/mock/following{/other_user}\",\n" +
                "        \"gists_url\": \"https://api.github.com/users/mock/gists{/gist_id}\",\n" +
                "        \"starred_url\": \"https://api.github.com/users/mock/starred{/owner}{/repo}\",\n" +
                "        \"subscriptions_url\": \"https://api.github.com/users/mock/subscriptions\",\n" +
                "        \"organizations_url\": \"https://api.github.com/users/mock/orgs\",\n" +
                "        \"repos_url\": \"https://api.github.com/users/mock/repos\",\n" +
                "        \"events_url\": \"https://api.github.com/users/mock/events{/privacy}\",\n" +
                "        \"received_events_url\": \"https://api.github.com/users/mock/received_events\",\n" +
                "        \"type\": \"User\",\n" +
                "        \"site_admin\": false\n" +
                "      },\n" +
                "      \"assignees\": [\n" +
                "        {\n" +
                "          \"login\": \"mock\",\n" +
                "          \"id\": 42354016,\n" +
                "          \"node_id\": \"MDQ6VXNlcjQyMzU0MDE2\",\n" +
                "          \"avatar_url\": \"https://avatars.githubusercontent.com/u/42354016?v=4\",\n" +
                "          \"gravatar_id\": \"\",\n" +
                "          \"url\": \"https://api.github.com/users/mock\",\n" +
                "          \"html_url\": \"https://github.com/mock\",\n" +
                "          \"followers_url\": \"https://api.github.com/users/mock/followers\",\n" +
                "          \"following_url\": \"https://api.github.com/users/mock/following{/other_user}\",\n" +
                "          \"gists_url\": \"https://api.github.com/users/mock/gists{/gist_id}\",\n" +
                "          \"starred_url\": \"https://api.github.com/users/mock/starred{/owner}{/repo}\",\n" +
                "          \"subscriptions_url\": \"https://api.github.com/users/mock/subscriptions\",\n" +
                "          \"organizations_url\": \"https://api.github.com/users/mock/orgs\",\n" +
                "          \"repos_url\": \"https://api.github.com/users/mock/repos\",\n" +
                "          \"events_url\": \"https://api.github.com/users/mock/events{/privacy}\",\n" +
                "          \"received_events_url\": \"https://api.github.com/users/mock/received_events\",\n" +
                "          \"type\": \"User\",\n" +
                "          \"site_admin\": false\n" +
                "        }\n" +
                "      ],\n" +
                "      \"milestone\": {\n" +
                "        \"url\": \"https://api.github.com/repos/mock/webhook/milestones/1\",\n" +
                "        \"html_url\": \"https://github.com/mock/webhook/milestone/1\",\n" +
                "        \"labels_url\": \"https://api.github.com/repos/mock/webhook/milestones/1/labels\",\n" +
                "        \"id\": 6442096,\n" +
                "        \"node_id\": \"MDk6TWlsZXN0b25lNjQ0MjA5Ng==\",\n" +
                "        \"number\": 1,\n" +
                "        \"title\": \"milestone\",\n" +
                "        \"description\": null,\n" +
                "        \"creator\": {\n" +
                "          \"login\": \"mock\",\n" +
                "          \"id\": 42354016,\n" +
                "          \"node_id\": \"MDQ6VXNlcjQyMzU0MDE2\",\n" +
                "          \"avatar_url\": \"https://avatars.githubusercontent.com/u/42354016?v=4\",\n" +
                "          \"gravatar_id\": \"\",\n" +
                "          \"url\": \"https://api.github.com/users/mock\",\n" +
                "          \"html_url\": \"https://github.com/mock\",\n" +
                "          \"followers_url\": \"https://api.github.com/users/mock/followers\",\n" +
                "          \"following_url\": \"https://api.github.com/users/mock/following{/other_user}\",\n" +
                "          \"gists_url\": \"https://api.github.com/users/mock/gists{/gist_id}\",\n" +
                "          \"starred_url\": \"https://api.github.com/users/mock/starred{/owner}{/repo}\",\n" +
                "          \"subscriptions_url\": \"https://api.github.com/users/mock/subscriptions\",\n" +
                "          \"organizations_url\": \"https://api.github.com/users/mock/orgs\",\n" +
                "          \"repos_url\": \"https://api.github.com/users/mock/repos\",\n" +
                "          \"events_url\": \"https://api.github.com/users/mock/events{/privacy}\",\n" +
                "          \"received_events_url\": \"https://api.github.com/users/mock/received_events\",\n" +
                "          \"type\": \"User\",\n" +
                "          \"site_admin\": false\n" +
                "        },\n" +
                "        \"open_issues\": 1,\n" +
                "        \"closed_issues\": 1,\n" +
                "        \"state\": \"open\",\n" +
                "        \"created_at\": \"2021-02-17T05:29:54Z\",\n" +
                "        \"updated_at\": \"2021-02-17T05:38:06Z\",\n" +
                "        \"due_on\": null,\n" +
                "        \"closed_at\": null\n" +
                "      },\n" +
                "      \"comments\": 0,\n" +
                "      \"created_at\": \"2021-02-17T05:33:48Z\",\n" +
                "      \"updated_at\": \"2021-02-17T05:38:06Z\",\n" +
                "      \"closed_at\": \"2021-02-17T05:38:06Z\",\n" +
                "      \"author_association\": \"OWNER\",\n" +
                "      \"active_lock_reason\": null,\n" +
                "      \"body\": \"Body\",\n" +
                "      \"performed_via_github_app\": null\n" +
                "    },\n" +
                "    \"repository\": {\n" +
                "      \"id\": 321581581,\n" +
                "      \"node_id\": \"MDEwOlJlcG9zaXRvcnkzMjE1ODE1ODE=\",\n" +
                "      \"name\": \"webhook\",\n" +
                "      \"full_name\": \"mock/webhook\",\n" +
                "      \"private\": true,\n" +
                "      \"owner\": {\n" +
                "        \"login\": \"mock\",\n" +
                "        \"id\": 42354016,\n" +
                "        \"node_id\": \"MDQ6VXNlcjQyMzU0MDE2\",\n" +
                "        \"avatar_url\": \"https://avatars.githubusercontent.com/u/42354016?v=4\",\n" +
                "        \"gravatar_id\": \"\",\n" +
                "        \"url\": \"https://api.github.com/users/mock\",\n" +
                "        \"html_url\": \"https://github.com/mock\",\n" +
                "        \"followers_url\": \"https://api.github.com/users/mock/followers\",\n" +
                "        \"following_url\": \"https://api.github.com/users/mock/following{/other_user}\",\n" +
                "        \"gists_url\": \"https://api.github.com/users/mock/gists{/gist_id}\",\n" +
                "        \"starred_url\": \"https://api.github.com/users/mock/starred{/owner}{/repo}\",\n" +
                "        \"subscriptions_url\": \"https://api.github.com/users/mock/subscriptions\",\n" +
                "        \"organizations_url\": \"https://api.github.com/users/mock/orgs\",\n" +
                "        \"repos_url\": \"https://api.github.com/users/mock/repos\",\n" +
                "        \"events_url\": \"https://api.github.com/users/mock/events{/privacy}\",\n" +
                "        \"received_events_url\": \"https://api.github.com/users/mock/received_events\",\n" +
                "        \"type\": \"User\",\n" +
                "        \"site_admin\": false\n" +
                "      },\n" +
                "      \"html_url\": \"https://github.com/mock/webhook\",\n" +
                "      \"description\": null,\n" +
                "      \"fork\": false,\n" +
                "      \"url\": \"https://api.github.com/repos/mock/webhook\",\n" +
                "      \"forks_url\": \"https://api.github.com/repos/mock/webhook/forks\",\n" +
                "      \"keys_url\": \"https://api.github.com/repos/mock/webhook/keys{/key_id}\",\n" +
                "      \"collaborators_url\": \"https://api.github.com/repos/mock/webhook/collaborators{/collaborator}\",\n" +
                "      \"teams_url\": \"https://api.github.com/repos/mock/webhook/teams\",\n" +
                "      \"hooks_url\": \"https://api.github.com/repos/mock/webhook/hooks\",\n" +
                "      \"issue_events_url\": \"https://api.github.com/repos/mock/webhook/issues/events{/number}\",\n" +
                "      \"events_url\": \"https://api.github.com/repos/mock/webhook/events\",\n" +
                "      \"assignees_url\": \"https://api.github.com/repos/mock/webhook/assignees{/user}\",\n" +
                "      \"branches_url\": \"https://api.github.com/repos/mock/webhook/branches{/branch}\",\n" +
                "      \"tags_url\": \"https://api.github.com/repos/mock/webhook/tags\",\n" +
                "      \"blobs_url\": \"https://api.github.com/repos/mock/webhook/git/blobs{/sha}\",\n" +
                "      \"git_tags_url\": \"https://api.github.com/repos/mock/webhook/git/tags{/sha}\",\n" +
                "      \"git_refs_url\": \"https://api.github.com/repos/mock/webhook/git/refs{/sha}\",\n" +
                "      \"trees_url\": \"https://api.github.com/repos/mock/webhook/git/trees{/sha}\",\n" +
                "      \"statuses_url\": \"https://api.github.com/repos/mock/webhook/statuses/{sha}\",\n" +
                "      \"languages_url\": \"https://api.github.com/repos/mock/webhook/languages\",\n" +
                "      \"stargazers_url\": \"https://api.github.com/repos/mock/webhook/stargazers\",\n" +
                "      \"contributors_url\": \"https://api.github.com/repos/mock/webhook/contributors\",\n" +
                "      \"subscribers_url\": \"https://api.github.com/repos/mock/webhook/subscribers\",\n" +
                "      \"subscription_url\": \"https://api.github.com/repos/mock/webhook/subscription\",\n" +
                "      \"commits_url\": \"https://api.github.com/repos/mock/webhook/commits{/sha}\",\n" +
                "      \"git_commits_url\": \"https://api.github.com/repos/mock/webhook/git/commits{/sha}\",\n" +
                "      \"comments_url\": \"https://api.github.com/repos/mock/webhook/comments{/number}\",\n" +
                "      \"issue_comment_url\": \"https://api.github.com/repos/mock/webhook/issues/comments{/number}\",\n" +
                "      \"contents_url\": \"https://api.github.com/repos/mock/webhook/contents/{+path}\",\n" +
                "      \"compare_url\": \"https://api.github.com/repos/mock/webhook/compare/{base}...{head}\",\n" +
                "      \"merges_url\": \"https://api.github.com/repos/mock/webhook/merges\",\n" +
                "      \"archive_url\": \"https://api.github.com/repos/mock/webhook/{archive_format}{/ref}\",\n" +
                "      \"downloads_url\": \"https://api.github.com/repos/mock/webhook/downloads\",\n" +
                "      \"issues_url\": \"https://api.github.com/repos/mock/webhook/issues{/number}\",\n" +
                "      \"pulls_url\": \"https://api.github.com/repos/mock/webhook/pulls{/number}\",\n" +
                "      \"milestones_url\": \"https://api.github.com/repos/mock/webhook/milestones{/number}\",\n" +
                "      \"notifications_url\": \"https://api.github.com/repos/mock/webhook/notifications{?since,all,participating}\",\n" +
                "      \"labels_url\": \"https://api.github.com/repos/mock/webhook/labels{/name}\",\n" +
                "      \"releases_url\": \"https://api.github.com/repos/mock/webhook/releases{/id}\",\n" +
                "      \"deployments_url\": \"https://api.github.com/repos/mock/webhook/deployments\",\n" +
                "      \"created_at\": \"2020-12-15T07:04:36Z\",\n" +
                "      \"updated_at\": \"2020-12-16T22:09:06Z\",\n" +
                "      \"pushed_at\": \"2020-12-16T22:09:04Z\",\n" +
                "      \"git_url\": \"git://github.com/mock/webhook.git\",\n" +
                "      \"ssh_url\": \"git@github.com:mock/webhook.git\",\n" +
                "      \"clone_url\": \"https://github.com/mock/webhook.git\",\n" +
                "      \"svn_url\": \"https://github.com/mock/webhook\",\n" +
                "      \"homepage\": null,\n" +
                "      \"size\": 82,\n" +
                "      \"stargazers_count\": 0,\n" +
                "      \"watchers_count\": 0,\n" +
                "      \"language\": \"Kotlin\",\n" +
                "      \"has_issues\": true,\n" +
                "      \"has_projects\": true,\n" +
                "      \"has_downloads\": true,\n" +
                "      \"has_wiki\": true,\n" +
                "      \"has_pages\": false,\n" +
                "      \"forks_count\": 0,\n" +
                "      \"mirror_url\": null,\n" +
                "      \"archived\": false,\n" +
                "      \"disabled\": false,\n" +
                "      \"open_issues_count\": 1,\n" +
                "      \"license\": null,\n" +
                "      \"forks\": 0,\n" +
                "      \"open_issues\": 1,\n" +
                "      \"watchers\": 0,\n" +
                "      \"default_branch\": \"main\"\n" +
                "    },\n" +
                "    \"sender\": {\n" +
                "      \"login\": \"mock\",\n" +
                "      \"id\": 42354016,\n" +
                "      \"node_id\": \"MDQ6VXNlcjQyMzU0MDE2\",\n" +
                "      \"avatar_url\": \"https://avatars.githubusercontent.com/u/42354016?v=4\",\n" +
                "      \"gravatar_id\": \"\",\n" +
                "      \"url\": \"https://api.github.com/users/mock\",\n" +
                "      \"html_url\": \"https://github.com/mock\",\n" +
                "      \"followers_url\": \"https://api.github.com/users/mock/followers\",\n" +
                "      \"following_url\": \"https://api.github.com/users/mock/following{/other_user}\",\n" +
                "      \"gists_url\": \"https://api.github.com/users/mock/gists{/gist_id}\",\n" +
                "      \"starred_url\": \"https://api.github.com/users/mock/starred{/owner}{/repo}\",\n" +
                "      \"subscriptions_url\": \"https://api.github.com/users/mock/subscriptions\",\n" +
                "      \"organizations_url\": \"https://api.github.com/users/mock/orgs\",\n" +
                "      \"repos_url\": \"https://api.github.com/users/mock/repos\",\n" +
                "      \"events_url\": \"https://api.github.com/users/mock/events{/privacy}\",\n" +
                "      \"received_events_url\": \"https://api.github.com/users/mock/received_events\",\n" +
                "      \"type\": \"User\",\n" +
                "      \"site_admin\": false\n" +
                "    }\n" +
                "  }"

        const val PAYLOAD_BODY: String = "{\n" +
                "    \"action\": \"closed\",\n" +
                "    \"issue\": {\n" +
                "      \"url\": \"https://api.github.com/repos/mock/webhook/issues/16\",\n" +
                "      \"repository_url\": \"https://api.github.com/repos/mock/webhook\",\n" +
                "      \"labels_url\": \"https://api.github.com/repos/mock/webhook/issues/16/labels{/name}\",\n" +
                "      \"comments_url\": \"https://api.github.com/repos/mock/webhook/issues/16/comments\",\n" +
                "      \"events_url\": \"https://api.github.com/repos/mock/webhook/issues/16/events\",\n" +
                "      \"html_url\": \"https://github.com/mock/webhook/issues/16\",\n" +
                "      \"id\": 809869512,\n" +
                "      \"node_id\": \"MDU6SXNzdWU4MDk4Njk1MTI=\",\n" +
                "      \"number\": 16,\n" +
                "      \"title\": \"titulo\",\n" +
                "      \"user\": {\n" +
                "        \"login\": \"mock\",\n" +
                "        \"id\": 42354016,\n" +
                "        \"node_id\": \"MDQ6VXNlcjQyMzU0MDE2\",\n" +
                "        \"avatar_url\": \"https://avatars.githubusercontent.com/u/42354016?v=4\",\n" +
                "        \"gravatar_id\": \"\",\n" +
                "        \"url\": \"https://api.github.com/users/mock\",\n" +
                "        \"html_url\": \"https://github.com/mock\",\n" +
                "        \"followers_url\": \"https://api.github.com/users/mock/followers\",\n" +
                "        \"following_url\": \"https://api.github.com/users/mock/following{/other_user}\",\n" +
                "        \"gists_url\": \"https://api.github.com/users/mock/gists{/gist_id}\",\n" +
                "        \"starred_url\": \"https://api.github.com/users/mock/starred{/owner}{/repo}\",\n" +
                "        \"subscriptions_url\": \"https://api.github.com/users/mock/subscriptions\",\n" +
                "        \"organizations_url\": \"https://api.github.com/users/mock/orgs\",\n" +
                "        \"repos_url\": \"https://api.github.com/users/mock/repos\",\n" +
                "        \"events_url\": \"https://api.github.com/users/mock/events{/privacy}\",\n" +
                "        \"received_events_url\": \"https://api.github.com/users/mock/received_events\",\n" +
                "        \"type\": \"User\",\n" +
                "        \"site_admin\": false\n" +
                "      },\n" +
                "      \"labels\": [],\n" +
                "      \"state\": \"closed\",\n" +
                "      \"locked\": false,\n" +
                "      \"assignee\": null,\n" +
                "      \"assignees\": [],\n" +
                "      \"milestone\": null,\n" +
                "      \"comments\": 0,\n" +
                "      \"created_at\": \"2021-02-17T05:33:48Z\",\n" +
                "      \"updated_at\": \"2021-02-17T05:38:06Z\",\n" +
                "      \"closed_at\": \"2021-02-17T05:38:06Z\",\n" +
                "      \"author_association\": \"OWNER\",\n" +
                "      \"active_lock_reason\": null,\n" +
                "      \"body\": \"Body\",\n" +
                "      \"performed_via_github_app\": null\n" +
                "    },\n" +
                "    \"repository\": {\n" +
                "      \"id\": 321581581,\n" +
                "      \"node_id\": \"MDEwOlJlcG9zaXRvcnkzMjE1ODE1ODE=\",\n" +
                "      \"name\": \"webhook\",\n" +
                "      \"full_name\": \"mock/webhook\",\n" +
                "      \"private\": true,\n" +
                "      \"owner\": {\n" +
                "        \"login\": \"mock\",\n" +
                "        \"id\": 42354016,\n" +
                "        \"node_id\": \"MDQ6VXNlcjQyMzU0MDE2\",\n" +
                "        \"avatar_url\": \"https://avatars.githubusercontent.com/u/42354016?v=4\",\n" +
                "        \"gravatar_id\": \"\",\n" +
                "        \"url\": \"https://api.github.com/users/mock\",\n" +
                "        \"html_url\": \"https://github.com/mock\",\n" +
                "        \"followers_url\": \"https://api.github.com/users/mock/followers\",\n" +
                "        \"following_url\": \"https://api.github.com/users/mock/following{/other_user}\",\n" +
                "        \"gists_url\": \"https://api.github.com/users/mock/gists{/gist_id}\",\n" +
                "        \"starred_url\": \"https://api.github.com/users/mock/starred{/owner}{/repo}\",\n" +
                "        \"subscriptions_url\": \"https://api.github.com/users/mock/subscriptions\",\n" +
                "        \"organizations_url\": \"https://api.github.com/users/mock/orgs\",\n" +
                "        \"repos_url\": \"https://api.github.com/users/mock/repos\",\n" +
                "        \"events_url\": \"https://api.github.com/users/mock/events{/privacy}\",\n" +
                "        \"received_events_url\": \"https://api.github.com/users/mock/received_events\",\n" +
                "        \"type\": \"User\",\n" +
                "        \"site_admin\": false\n" +
                "      },\n" +
                "      \"html_url\": \"https://github.com/mock/webhook\",\n" +
                "      \"description\": null,\n" +
                "      \"fork\": false,\n" +
                "      \"url\": \"https://api.github.com/repos/mock/webhook\",\n" +
                "      \"forks_url\": \"https://api.github.com/repos/mock/webhook/forks\",\n" +
                "      \"keys_url\": \"https://api.github.com/repos/mock/webhook/keys{/key_id}\",\n" +
                "      \"collaborators_url\": \"https://api.github.com/repos/mock/webhook/collaborators{/collaborator}\",\n" +
                "      \"teams_url\": \"https://api.github.com/repos/mock/webhook/teams\",\n" +
                "      \"hooks_url\": \"https://api.github.com/repos/mock/webhook/hooks\",\n" +
                "      \"issue_events_url\": \"https://api.github.com/repos/mock/webhook/issues/events{/number}\",\n" +
                "      \"events_url\": \"https://api.github.com/repos/mock/webhook/events\",\n" +
                "      \"assignees_url\": \"https://api.github.com/repos/mock/webhook/assignees{/user}\",\n" +
                "      \"branches_url\": \"https://api.github.com/repos/mock/webhook/branches{/branch}\",\n" +
                "      \"tags_url\": \"https://api.github.com/repos/mock/webhook/tags\",\n" +
                "      \"blobs_url\": \"https://api.github.com/repos/mock/webhook/git/blobs{/sha}\",\n" +
                "      \"git_tags_url\": \"https://api.github.com/repos/mock/webhook/git/tags{/sha}\",\n" +
                "      \"git_refs_url\": \"https://api.github.com/repos/mock/webhook/git/refs{/sha}\",\n" +
                "      \"trees_url\": \"https://api.github.com/repos/mock/webhook/git/trees{/sha}\",\n" +
                "      \"statuses_url\": \"https://api.github.com/repos/mock/webhook/statuses/{sha}\",\n" +
                "      \"languages_url\": \"https://api.github.com/repos/mock/webhook/languages\",\n" +
                "      \"stargazers_url\": \"https://api.github.com/repos/mock/webhook/stargazers\",\n" +
                "      \"contributors_url\": \"https://api.github.com/repos/mock/webhook/contributors\",\n" +
                "      \"subscribers_url\": \"https://api.github.com/repos/mock/webhook/subscribers\",\n" +
                "      \"subscription_url\": \"https://api.github.com/repos/mock/webhook/subscription\",\n" +
                "      \"commits_url\": \"https://api.github.com/repos/mock/webhook/commits{/sha}\",\n" +
                "      \"git_commits_url\": \"https://api.github.com/repos/mock/webhook/git/commits{/sha}\",\n" +
                "      \"comments_url\": \"https://api.github.com/repos/mock/webhook/comments{/number}\",\n" +
                "      \"issue_comment_url\": \"https://api.github.com/repos/mock/webhook/issues/comments{/number}\",\n" +
                "      \"contents_url\": \"https://api.github.com/repos/mock/webhook/contents/{+path}\",\n" +
                "      \"compare_url\": \"https://api.github.com/repos/mock/webhook/compare/{base}...{head}\",\n" +
                "      \"merges_url\": \"https://api.github.com/repos/mock/webhook/merges\",\n" +
                "      \"archive_url\": \"https://api.github.com/repos/mock/webhook/{archive_format}{/ref}\",\n" +
                "      \"downloads_url\": \"https://api.github.com/repos/mock/webhook/downloads\",\n" +
                "      \"issues_url\": \"https://api.github.com/repos/mock/webhook/issues{/number}\",\n" +
                "      \"pulls_url\": \"https://api.github.com/repos/mock/webhook/pulls{/number}\",\n" +
                "      \"milestones_url\": \"https://api.github.com/repos/mock/webhook/milestones{/number}\",\n" +
                "      \"notifications_url\": \"https://api.github.com/repos/mock/webhook/notifications{?since,all,participating}\",\n" +
                "      \"labels_url\": \"https://api.github.com/repos/mock/webhook/labels{/name}\",\n" +
                "      \"releases_url\": \"https://api.github.com/repos/mock/webhook/releases{/id}\",\n" +
                "      \"deployments_url\": \"https://api.github.com/repos/mock/webhook/deployments\",\n" +
                "      \"created_at\": \"2020-12-15T07:04:36Z\",\n" +
                "      \"updated_at\": \"2020-12-16T22:09:06Z\",\n" +
                "      \"pushed_at\": \"2020-12-16T22:09:04Z\",\n" +
                "      \"git_url\": \"git://github.com/mock/webhook.git\",\n" +
                "      \"ssh_url\": \"git@github.com:mock/webhook.git\",\n" +
                "      \"clone_url\": \"https://github.com/mock/webhook.git\",\n" +
                "      \"svn_url\": \"https://github.com/mock/webhook\",\n" +
                "      \"homepage\": null,\n" +
                "      \"size\": 82,\n" +
                "      \"stargazers_count\": 0,\n" +
                "      \"watchers_count\": 0,\n" +
                "      \"language\": \"Kotlin\",\n" +
                "      \"has_issues\": true,\n" +
                "      \"has_projects\": true,\n" +
                "      \"has_downloads\": true,\n" +
                "      \"has_wiki\": true,\n" +
                "      \"has_pages\": false,\n" +
                "      \"forks_count\": 0,\n" +
                "      \"mirror_url\": null,\n" +
                "      \"archived\": false,\n" +
                "      \"disabled\": false,\n" +
                "      \"open_issues_count\": 1,\n" +
                "      \"license\": null,\n" +
                "      \"forks\": 0,\n" +
                "      \"open_issues\": 1,\n" +
                "      \"watchers\": 0,\n" +
                "      \"default_branch\": \"main\"\n" +
                "    },\n" +
                "    \"sender\": {\n" +
                "      \"login\": \"mock\",\n" +
                "      \"id\": 42354016,\n" +
                "      \"node_id\": \"MDQ6VXNlcjQyMzU0MDE2\",\n" +
                "      \"avatar_url\": \"https://avatars.githubusercontent.com/u/42354016?v=4\",\n" +
                "      \"gravatar_id\": \"\",\n" +
                "      \"url\": \"https://api.github.com/users/mock\",\n" +
                "      \"html_url\": \"https://github.com/mock\",\n" +
                "      \"followers_url\": \"https://api.github.com/users/mock/followers\",\n" +
                "      \"following_url\": \"https://api.github.com/users/mock/following{/other_user}\",\n" +
                "      \"gists_url\": \"https://api.github.com/users/mock/gists{/gist_id}\",\n" +
                "      \"starred_url\": \"https://api.github.com/users/mock/starred{/owner}{/repo}\",\n" +
                "      \"subscriptions_url\": \"https://api.github.com/users/mock/subscriptions\",\n" +
                "      \"organizations_url\": \"https://api.github.com/users/mock/orgs\",\n" +
                "      \"repos_url\": \"https://api.github.com/users/mock/repos\",\n" +
                "      \"events_url\": \"https://api.github.com/users/mock/events{/privacy}\",\n" +
                "      \"received_events_url\": \"https://api.github.com/users/mock/received_events\",\n" +
                "      \"type\": \"User\",\n" +
                "      \"site_admin\": false\n" +
                "    }\n" +
                "  }"

        const val PAYLOAD_LABEL: String = "{\n" +
                "    \"action\": \"closed\",\n" +
                "    \"issue\": {\n" +
                "      \"url\": \"https://api.github.com/repos/mock/webhook/issues/16\",\n" +
                "      \"repository_url\": \"https://api.github.com/repos/mock/webhook\",\n" +
                "      \"labels_url\": \"https://api.github.com/repos/mock/webhook/issues/16/labels{/name}\",\n" +
                "      \"comments_url\": \"https://api.github.com/repos/mock/webhook/issues/16/comments\",\n" +
                "      \"events_url\": \"https://api.github.com/repos/mock/webhook/issues/16/events\",\n" +
                "      \"html_url\": \"https://github.com/mock/webhook/issues/16\",\n" +
                "      \"id\": 809869512,\n" +
                "      \"node_id\": \"MDU6SXNzdWU4MDk4Njk1MTI=\",\n" +
                "      \"number\": 16,\n" +
                "      \"title\": \"titulo\",\n" +
                "      \"user\": {\n" +
                "        \"login\": \"mock\",\n" +
                "        \"id\": 42354016,\n" +
                "        \"node_id\": \"MDQ6VXNlcjQyMzU0MDE2\",\n" +
                "        \"avatar_url\": \"https://avatars.githubusercontent.com/u/42354016?v=4\",\n" +
                "        \"gravatar_id\": \"\",\n" +
                "        \"url\": \"https://api.github.com/users/mock\",\n" +
                "        \"html_url\": \"https://github.com/mock\",\n" +
                "        \"followers_url\": \"https://api.github.com/users/mock/followers\",\n" +
                "        \"following_url\": \"https://api.github.com/users/mock/following{/other_user}\",\n" +
                "        \"gists_url\": \"https://api.github.com/users/mock/gists{/gist_id}\",\n" +
                "        \"starred_url\": \"https://api.github.com/users/mock/starred{/owner}{/repo}\",\n" +
                "        \"subscriptions_url\": \"https://api.github.com/users/mock/subscriptions\",\n" +
                "        \"organizations_url\": \"https://api.github.com/users/mock/orgs\",\n" +
                "        \"repos_url\": \"https://api.github.com/users/mock/repos\",\n" +
                "        \"events_url\": \"https://api.github.com/users/mock/events{/privacy}\",\n" +
                "        \"received_events_url\": \"https://api.github.com/users/mock/received_events\",\n" +
                "        \"type\": \"User\",\n" +
                "        \"site_admin\": false\n" +
                "      },\n" +
                "      \"labels\": [\n" +
                "        {\n" +
                "          \"id\": 2584689276,\n" +
                "          \"node_id\": \"MDU6TGFiZWwyNTg0Njg5Mjc2\",\n" +
                "          \"url\": \"https://api.github.com/repos/mock/webhook/labels/bug\",\n" +
                "          \"name\": \"bug\",\n" +
                "          \"color\": \"d73a4a\",\n" +
                "          \"default\": true,\n" +
                "          \"description\": \"Something isn't working\"\n" +
                "        }\n" +
                "      ],\n" +
                "      \"state\": \"closed\",\n" +
                "      \"locked\": false,\n" +
                "      \"assignee\": null,\n" +
                "      \"assignees\": [],\n" +
                "      \"milestone\": null,\n" +
                "      \"comments\": 0,\n" +
                "      \"created_at\": \"2021-02-17T05:33:48Z\",\n" +
                "      \"updated_at\": \"2021-02-17T05:38:06Z\",\n" +
                "      \"closed_at\": \"2021-02-17T05:38:06Z\",\n" +
                "      \"author_association\": \"OWNER\",\n" +
                "      \"active_lock_reason\": null,\n" +
                "      \"body\": \" \",\n" +
                "      \"performed_via_github_app\": null\n" +
                "    },\n" +
                "    \"repository\": {\n" +
                "      \"id\": 321581581,\n" +
                "      \"node_id\": \"MDEwOlJlcG9zaXRvcnkzMjE1ODE1ODE=\",\n" +
                "      \"name\": \"webhook\",\n" +
                "      \"full_name\": \"mock/webhook\",\n" +
                "      \"private\": true,\n" +
                "      \"owner\": {\n" +
                "        \"login\": \"mock\",\n" +
                "        \"id\": 42354016,\n" +
                "        \"node_id\": \"MDQ6VXNlcjQyMzU0MDE2\",\n" +
                "        \"avatar_url\": \"https://avatars.githubusercontent.com/u/42354016?v=4\",\n" +
                "        \"gravatar_id\": \"\",\n" +
                "        \"url\": \"https://api.github.com/users/mock\",\n" +
                "        \"html_url\": \"https://github.com/mock\",\n" +
                "        \"followers_url\": \"https://api.github.com/users/mock/followers\",\n" +
                "        \"following_url\": \"https://api.github.com/users/mock/following{/other_user}\",\n" +
                "        \"gists_url\": \"https://api.github.com/users/mock/gists{/gist_id}\",\n" +
                "        \"starred_url\": \"https://api.github.com/users/mock/starred{/owner}{/repo}\",\n" +
                "        \"subscriptions_url\": \"https://api.github.com/users/mock/subscriptions\",\n" +
                "        \"organizations_url\": \"https://api.github.com/users/mock/orgs\",\n" +
                "        \"repos_url\": \"https://api.github.com/users/mock/repos\",\n" +
                "        \"events_url\": \"https://api.github.com/users/mock/events{/privacy}\",\n" +
                "        \"received_events_url\": \"https://api.github.com/users/mock/received_events\",\n" +
                "        \"type\": \"User\",\n" +
                "        \"site_admin\": false\n" +
                "      },\n" +
                "      \"html_url\": \"https://github.com/mock/webhook\",\n" +
                "      \"description\": null,\n" +
                "      \"fork\": false,\n" +
                "      \"url\": \"https://api.github.com/repos/mock/webhook\",\n" +
                "      \"forks_url\": \"https://api.github.com/repos/mock/webhook/forks\",\n" +
                "      \"keys_url\": \"https://api.github.com/repos/mock/webhook/keys{/key_id}\",\n" +
                "      \"collaborators_url\": \"https://api.github.com/repos/mock/webhook/collaborators{/collaborator}\",\n" +
                "      \"teams_url\": \"https://api.github.com/repos/mock/webhook/teams\",\n" +
                "      \"hooks_url\": \"https://api.github.com/repos/mock/webhook/hooks\",\n" +
                "      \"issue_events_url\": \"https://api.github.com/repos/mock/webhook/issues/events{/number}\",\n" +
                "      \"events_url\": \"https://api.github.com/repos/mock/webhook/events\",\n" +
                "      \"assignees_url\": \"https://api.github.com/repos/mock/webhook/assignees{/user}\",\n" +
                "      \"branches_url\": \"https://api.github.com/repos/mock/webhook/branches{/branch}\",\n" +
                "      \"tags_url\": \"https://api.github.com/repos/mock/webhook/tags\",\n" +
                "      \"blobs_url\": \"https://api.github.com/repos/mock/webhook/git/blobs{/sha}\",\n" +
                "      \"git_tags_url\": \"https://api.github.com/repos/mock/webhook/git/tags{/sha}\",\n" +
                "      \"git_refs_url\": \"https://api.github.com/repos/mock/webhook/git/refs{/sha}\",\n" +
                "      \"trees_url\": \"https://api.github.com/repos/mock/webhook/git/trees{/sha}\",\n" +
                "      \"statuses_url\": \"https://api.github.com/repos/mock/webhook/statuses/{sha}\",\n" +
                "      \"languages_url\": \"https://api.github.com/repos/mock/webhook/languages\",\n" +
                "      \"stargazers_url\": \"https://api.github.com/repos/mock/webhook/stargazers\",\n" +
                "      \"contributors_url\": \"https://api.github.com/repos/mock/webhook/contributors\",\n" +
                "      \"subscribers_url\": \"https://api.github.com/repos/mock/webhook/subscribers\",\n" +
                "      \"subscription_url\": \"https://api.github.com/repos/mock/webhook/subscription\",\n" +
                "      \"commits_url\": \"https://api.github.com/repos/mock/webhook/commits{/sha}\",\n" +
                "      \"git_commits_url\": \"https://api.github.com/repos/mock/webhook/git/commits{/sha}\",\n" +
                "      \"comments_url\": \"https://api.github.com/repos/mock/webhook/comments{/number}\",\n" +
                "      \"issue_comment_url\": \"https://api.github.com/repos/mock/webhook/issues/comments{/number}\",\n" +
                "      \"contents_url\": \"https://api.github.com/repos/mock/webhook/contents/{+path}\",\n" +
                "      \"compare_url\": \"https://api.github.com/repos/mock/webhook/compare/{base}...{head}\",\n" +
                "      \"merges_url\": \"https://api.github.com/repos/mock/webhook/merges\",\n" +
                "      \"archive_url\": \"https://api.github.com/repos/mock/webhook/{archive_format}{/ref}\",\n" +
                "      \"downloads_url\": \"https://api.github.com/repos/mock/webhook/downloads\",\n" +
                "      \"issues_url\": \"https://api.github.com/repos/mock/webhook/issues{/number}\",\n" +
                "      \"pulls_url\": \"https://api.github.com/repos/mock/webhook/pulls{/number}\",\n" +
                "      \"milestones_url\": \"https://api.github.com/repos/mock/webhook/milestones{/number}\",\n" +
                "      \"notifications_url\": \"https://api.github.com/repos/mock/webhook/notifications{?since,all,participating}\",\n" +
                "      \"labels_url\": \"https://api.github.com/repos/mock/webhook/labels{/name}\",\n" +
                "      \"releases_url\": \"https://api.github.com/repos/mock/webhook/releases{/id}\",\n" +
                "      \"deployments_url\": \"https://api.github.com/repos/mock/webhook/deployments\",\n" +
                "      \"created_at\": \"2020-12-15T07:04:36Z\",\n" +
                "      \"updated_at\": \"2020-12-16T22:09:06Z\",\n" +
                "      \"pushed_at\": \"2020-12-16T22:09:04Z\",\n" +
                "      \"git_url\": \"git://github.com/mock/webhook.git\",\n" +
                "      \"ssh_url\": \"git@github.com:mock/webhook.git\",\n" +
                "      \"clone_url\": \"https://github.com/mock/webhook.git\",\n" +
                "      \"svn_url\": \"https://github.com/mock/webhook\",\n" +
                "      \"homepage\": null,\n" +
                "      \"size\": 82,\n" +
                "      \"stargazers_count\": 0,\n" +
                "      \"watchers_count\": 0,\n" +
                "      \"language\": \"Kotlin\",\n" +
                "      \"has_issues\": true,\n" +
                "      \"has_projects\": true,\n" +
                "      \"has_downloads\": true,\n" +
                "      \"has_wiki\": true,\n" +
                "      \"has_pages\": false,\n" +
                "      \"forks_count\": 0,\n" +
                "      \"mirror_url\": null,\n" +
                "      \"archived\": false,\n" +
                "      \"disabled\": false,\n" +
                "      \"open_issues_count\": 1,\n" +
                "      \"license\": null,\n" +
                "      \"forks\": 0,\n" +
                "      \"open_issues\": 1,\n" +
                "      \"watchers\": 0,\n" +
                "      \"default_branch\": \"main\"\n" +
                "    },\n" +
                "    \"sender\": {\n" +
                "      \"login\": \"mock\",\n" +
                "      \"id\": 42354016,\n" +
                "      \"node_id\": \"MDQ6VXNlcjQyMzU0MDE2\",\n" +
                "      \"avatar_url\": \"https://avatars.githubusercontent.com/u/42354016?v=4\",\n" +
                "      \"gravatar_id\": \"\",\n" +
                "      \"url\": \"https://api.github.com/users/mock\",\n" +
                "      \"html_url\": \"https://github.com/mock\",\n" +
                "      \"followers_url\": \"https://api.github.com/users/mock/followers\",\n" +
                "      \"following_url\": \"https://api.github.com/users/mock/following{/other_user}\",\n" +
                "      \"gists_url\": \"https://api.github.com/users/mock/gists{/gist_id}\",\n" +
                "      \"starred_url\": \"https://api.github.com/users/mock/starred{/owner}{/repo}\",\n" +
                "      \"subscriptions_url\": \"https://api.github.com/users/mock/subscriptions\",\n" +
                "      \"organizations_url\": \"https://api.github.com/users/mock/orgs\",\n" +
                "      \"repos_url\": \"https://api.github.com/users/mock/repos\",\n" +
                "      \"events_url\": \"https://api.github.com/users/mock/events{/privacy}\",\n" +
                "      \"received_events_url\": \"https://api.github.com/users/mock/received_events\",\n" +
                "      \"type\": \"User\",\n" +
                "      \"site_admin\": false\n" +
                "    }\n" +
                "  }"

        const val PAYLOAD_ASSIGNEE: String = "{\n" +
                "    \"action\": \"closed\",\n" +
                "    \"issue\": {\n" +
                "      \"url\": \"https://api.github.com/repos/mock/webhook/issues/16\",\n" +
                "      \"repository_url\": \"https://api.github.com/repos/mock/webhook\",\n" +
                "      \"labels_url\": \"https://api.github.com/repos/mock/webhook/issues/16/labels{/name}\",\n" +
                "      \"comments_url\": \"https://api.github.com/repos/mock/webhook/issues/16/comments\",\n" +
                "      \"events_url\": \"https://api.github.com/repos/mock/webhook/issues/16/events\",\n" +
                "      \"html_url\": \"https://github.com/mock/webhook/issues/16\",\n" +
                "      \"id\": 809869512,\n" +
                "      \"node_id\": \"MDU6SXNzdWU4MDk4Njk1MTI=\",\n" +
                "      \"number\": 16,\n" +
                "      \"title\": \"titulo\",\n" +
                "      \"user\": {\n" +
                "        \"login\": \"mock\",\n" +
                "        \"id\": 42354016,\n" +
                "        \"node_id\": \"MDQ6VXNlcjQyMzU0MDE2\",\n" +
                "        \"avatar_url\": \"https://avatars.githubusercontent.com/u/42354016?v=4\",\n" +
                "        \"gravatar_id\": \"\",\n" +
                "        \"url\": \"https://api.github.com/users/mock\",\n" +
                "        \"html_url\": \"https://github.com/mock\",\n" +
                "        \"followers_url\": \"https://api.github.com/users/mock/followers\",\n" +
                "        \"following_url\": \"https://api.github.com/users/mock/following{/other_user}\",\n" +
                "        \"gists_url\": \"https://api.github.com/users/mock/gists{/gist_id}\",\n" +
                "        \"starred_url\": \"https://api.github.com/users/mock/starred{/owner}{/repo}\",\n" +
                "        \"subscriptions_url\": \"https://api.github.com/users/mock/subscriptions\",\n" +
                "        \"organizations_url\": \"https://api.github.com/users/mock/orgs\",\n" +
                "        \"repos_url\": \"https://api.github.com/users/mock/repos\",\n" +
                "        \"events_url\": \"https://api.github.com/users/mock/events{/privacy}\",\n" +
                "        \"received_events_url\": \"https://api.github.com/users/mock/received_events\",\n" +
                "        \"type\": \"User\",\n" +
                "        \"site_admin\": false\n" +
                "      },\n" +
                "      \"labels\": [ ],\n" +
                "      \"state\": \"closed\",\n" +
                "      \"locked\": false,\n" +
                "      \"assignee\": {\n" +
                "        \"login\": \"mock\",\n" +
                "        \"id\": 42354016,\n" +
                "        \"node_id\": \"MDQ6VXNlcjQyMzU0MDE2\",\n" +
                "        \"avatar_url\": \"https://avatars.githubusercontent.com/u/42354016?v=4\",\n" +
                "        \"gravatar_id\": \"\",\n" +
                "        \"url\": \"https://api.github.com/users/mock\",\n" +
                "        \"html_url\": \"https://github.com/mock\",\n" +
                "        \"followers_url\": \"https://api.github.com/users/mock/followers\",\n" +
                "        \"following_url\": \"https://api.github.com/users/mock/following{/other_user}\",\n" +
                "        \"gists_url\": \"https://api.github.com/users/mock/gists{/gist_id}\",\n" +
                "        \"starred_url\": \"https://api.github.com/users/mock/starred{/owner}{/repo}\",\n" +
                "        \"subscriptions_url\": \"https://api.github.com/users/mock/subscriptions\",\n" +
                "        \"organizations_url\": \"https://api.github.com/users/mock/orgs\",\n" +
                "        \"repos_url\": \"https://api.github.com/users/mock/repos\",\n" +
                "        \"events_url\": \"https://api.github.com/users/mock/events{/privacy}\",\n" +
                "        \"received_events_url\": \"https://api.github.com/users/mock/received_events\",\n" +
                "        \"type\": \"User\",\n" +
                "        \"site_admin\": false\n" +
                "      },\n" +
                "      \"assignees\": [\n" +
                "        {\n" +
                "          \"login\": \"mock\",\n" +
                "          \"id\": 42354016,\n" +
                "          \"node_id\": \"MDQ6VXNlcjQyMzU0MDE2\",\n" +
                "          \"avatar_url\": \"https://avatars.githubusercontent.com/u/42354016?v=4\",\n" +
                "          \"gravatar_id\": \"\",\n" +
                "          \"url\": \"https://api.github.com/users/mock\",\n" +
                "          \"html_url\": \"https://github.com/mock\",\n" +
                "          \"followers_url\": \"https://api.github.com/users/mock/followers\",\n" +
                "          \"following_url\": \"https://api.github.com/users/mock/following{/other_user}\",\n" +
                "          \"gists_url\": \"https://api.github.com/users/mock/gists{/gist_id}\",\n" +
                "          \"starred_url\": \"https://api.github.com/users/mock/starred{/owner}{/repo}\",\n" +
                "          \"subscriptions_url\": \"https://api.github.com/users/mock/subscriptions\",\n" +
                "          \"organizations_url\": \"https://api.github.com/users/mock/orgs\",\n" +
                "          \"repos_url\": \"https://api.github.com/users/mock/repos\",\n" +
                "          \"events_url\": \"https://api.github.com/users/mock/events{/privacy}\",\n" +
                "          \"received_events_url\": \"https://api.github.com/users/mock/received_events\",\n" +
                "          \"type\": \"User\",\n" +
                "          \"site_admin\": false\n" +
                "        }\n" +
                "      ],\n" +
                "      \"milestone\": null,\n" +
                "      \"comments\": 0,\n" +
                "      \"created_at\": \"2021-02-17T05:33:48Z\",\n" +
                "      \"updated_at\": \"2021-02-17T05:38:06Z\",\n" +
                "      \"closed_at\": \"2021-02-17T05:38:06Z\",\n" +
                "      \"author_association\": \"OWNER\",\n" +
                "      \"active_lock_reason\": null,\n" +
                "      \"body\": \" \",\n" +
                "      \"performed_via_github_app\": null\n" +
                "    },\n" +
                "    \"repository\": {\n" +
                "      \"id\": 321581581,\n" +
                "      \"node_id\": \"MDEwOlJlcG9zaXRvcnkzMjE1ODE1ODE=\",\n" +
                "      \"name\": \"webhook\",\n" +
                "      \"full_name\": \"mock/webhook\",\n" +
                "      \"private\": true,\n" +
                "      \"owner\": {\n" +
                "        \"login\": \"mock\",\n" +
                "        \"id\": 42354016,\n" +
                "        \"node_id\": \"MDQ6VXNlcjQyMzU0MDE2\",\n" +
                "        \"avatar_url\": \"https://avatars.githubusercontent.com/u/42354016?v=4\",\n" +
                "        \"gravatar_id\": \"\",\n" +
                "        \"url\": \"https://api.github.com/users/mock\",\n" +
                "        \"html_url\": \"https://github.com/mock\",\n" +
                "        \"followers_url\": \"https://api.github.com/users/mock/followers\",\n" +
                "        \"following_url\": \"https://api.github.com/users/mock/following{/other_user}\",\n" +
                "        \"gists_url\": \"https://api.github.com/users/mock/gists{/gist_id}\",\n" +
                "        \"starred_url\": \"https://api.github.com/users/mock/starred{/owner}{/repo}\",\n" +
                "        \"subscriptions_url\": \"https://api.github.com/users/mock/subscriptions\",\n" +
                "        \"organizations_url\": \"https://api.github.com/users/mock/orgs\",\n" +
                "        \"repos_url\": \"https://api.github.com/users/mock/repos\",\n" +
                "        \"events_url\": \"https://api.github.com/users/mock/events{/privacy}\",\n" +
                "        \"received_events_url\": \"https://api.github.com/users/mock/received_events\",\n" +
                "        \"type\": \"User\",\n" +
                "        \"site_admin\": false\n" +
                "      },\n" +
                "      \"html_url\": \"https://github.com/mock/webhook\",\n" +
                "      \"description\": null,\n" +
                "      \"fork\": false,\n" +
                "      \"url\": \"https://api.github.com/repos/mock/webhook\",\n" +
                "      \"forks_url\": \"https://api.github.com/repos/mock/webhook/forks\",\n" +
                "      \"keys_url\": \"https://api.github.com/repos/mock/webhook/keys{/key_id}\",\n" +
                "      \"collaborators_url\": \"https://api.github.com/repos/mock/webhook/collaborators{/collaborator}\",\n" +
                "      \"teams_url\": \"https://api.github.com/repos/mock/webhook/teams\",\n" +
                "      \"hooks_url\": \"https://api.github.com/repos/mock/webhook/hooks\",\n" +
                "      \"issue_events_url\": \"https://api.github.com/repos/mock/webhook/issues/events{/number}\",\n" +
                "      \"events_url\": \"https://api.github.com/repos/mock/webhook/events\",\n" +
                "      \"assignees_url\": \"https://api.github.com/repos/mock/webhook/assignees{/user}\",\n" +
                "      \"branches_url\": \"https://api.github.com/repos/mock/webhook/branches{/branch}\",\n" +
                "      \"tags_url\": \"https://api.github.com/repos/mock/webhook/tags\",\n" +
                "      \"blobs_url\": \"https://api.github.com/repos/mock/webhook/git/blobs{/sha}\",\n" +
                "      \"git_tags_url\": \"https://api.github.com/repos/mock/webhook/git/tags{/sha}\",\n" +
                "      \"git_refs_url\": \"https://api.github.com/repos/mock/webhook/git/refs{/sha}\",\n" +
                "      \"trees_url\": \"https://api.github.com/repos/mock/webhook/git/trees{/sha}\",\n" +
                "      \"statuses_url\": \"https://api.github.com/repos/mock/webhook/statuses/{sha}\",\n" +
                "      \"languages_url\": \"https://api.github.com/repos/mock/webhook/languages\",\n" +
                "      \"stargazers_url\": \"https://api.github.com/repos/mock/webhook/stargazers\",\n" +
                "      \"contributors_url\": \"https://api.github.com/repos/mock/webhook/contributors\",\n" +
                "      \"subscribers_url\": \"https://api.github.com/repos/mock/webhook/subscribers\",\n" +
                "      \"subscription_url\": \"https://api.github.com/repos/mock/webhook/subscription\",\n" +
                "      \"commits_url\": \"https://api.github.com/repos/mock/webhook/commits{/sha}\",\n" +
                "      \"git_commits_url\": \"https://api.github.com/repos/mock/webhook/git/commits{/sha}\",\n" +
                "      \"comments_url\": \"https://api.github.com/repos/mock/webhook/comments{/number}\",\n" +
                "      \"issue_comment_url\": \"https://api.github.com/repos/mock/webhook/issues/comments{/number}\",\n" +
                "      \"contents_url\": \"https://api.github.com/repos/mock/webhook/contents/{+path}\",\n" +
                "      \"compare_url\": \"https://api.github.com/repos/mock/webhook/compare/{base}...{head}\",\n" +
                "      \"merges_url\": \"https://api.github.com/repos/mock/webhook/merges\",\n" +
                "      \"archive_url\": \"https://api.github.com/repos/mock/webhook/{archive_format}{/ref}\",\n" +
                "      \"downloads_url\": \"https://api.github.com/repos/mock/webhook/downloads\",\n" +
                "      \"issues_url\": \"https://api.github.com/repos/mock/webhook/issues{/number}\",\n" +
                "      \"pulls_url\": \"https://api.github.com/repos/mock/webhook/pulls{/number}\",\n" +
                "      \"milestones_url\": \"https://api.github.com/repos/mock/webhook/milestones{/number}\",\n" +
                "      \"notifications_url\": \"https://api.github.com/repos/mock/webhook/notifications{?since,all,participating}\",\n" +
                "      \"labels_url\": \"https://api.github.com/repos/mock/webhook/labels{/name}\",\n" +
                "      \"releases_url\": \"https://api.github.com/repos/mock/webhook/releases{/id}\",\n" +
                "      \"deployments_url\": \"https://api.github.com/repos/mock/webhook/deployments\",\n" +
                "      \"created_at\": \"2020-12-15T07:04:36Z\",\n" +
                "      \"updated_at\": \"2020-12-16T22:09:06Z\",\n" +
                "      \"pushed_at\": \"2020-12-16T22:09:04Z\",\n" +
                "      \"git_url\": \"git://github.com/mock/webhook.git\",\n" +
                "      \"ssh_url\": \"git@github.com:mock/webhook.git\",\n" +
                "      \"clone_url\": \"https://github.com/mock/webhook.git\",\n" +
                "      \"svn_url\": \"https://github.com/mock/webhook\",\n" +
                "      \"homepage\": null,\n" +
                "      \"size\": 82,\n" +
                "      \"stargazers_count\": 0,\n" +
                "      \"watchers_count\": 0,\n" +
                "      \"language\": \"Kotlin\",\n" +
                "      \"has_issues\": true,\n" +
                "      \"has_projects\": true,\n" +
                "      \"has_downloads\": true,\n" +
                "      \"has_wiki\": true,\n" +
                "      \"has_pages\": false,\n" +
                "      \"forks_count\": 0,\n" +
                "      \"mirror_url\": null,\n" +
                "      \"archived\": false,\n" +
                "      \"disabled\": false,\n" +
                "      \"open_issues_count\": 1,\n" +
                "      \"license\": null,\n" +
                "      \"forks\": 0,\n" +
                "      \"open_issues\": 1,\n" +
                "      \"watchers\": 0,\n" +
                "      \"default_branch\": \"main\"\n" +
                "    },\n" +
                "    \"sender\": {\n" +
                "      \"login\": \"mock\",\n" +
                "      \"id\": 42354016,\n" +
                "      \"node_id\": \"MDQ6VXNlcjQyMzU0MDE2\",\n" +
                "      \"avatar_url\": \"https://avatars.githubusercontent.com/u/42354016?v=4\",\n" +
                "      \"gravatar_id\": \"\",\n" +
                "      \"url\": \"https://api.github.com/users/mock\",\n" +
                "      \"html_url\": \"https://github.com/mock\",\n" +
                "      \"followers_url\": \"https://api.github.com/users/mock/followers\",\n" +
                "      \"following_url\": \"https://api.github.com/users/mock/following{/other_user}\",\n" +
                "      \"gists_url\": \"https://api.github.com/users/mock/gists{/gist_id}\",\n" +
                "      \"starred_url\": \"https://api.github.com/users/mock/starred{/owner}{/repo}\",\n" +
                "      \"subscriptions_url\": \"https://api.github.com/users/mock/subscriptions\",\n" +
                "      \"organizations_url\": \"https://api.github.com/users/mock/orgs\",\n" +
                "      \"repos_url\": \"https://api.github.com/users/mock/repos\",\n" +
                "      \"events_url\": \"https://api.github.com/users/mock/events{/privacy}\",\n" +
                "      \"received_events_url\": \"https://api.github.com/users/mock/received_events\",\n" +
                "      \"type\": \"User\",\n" +
                "      \"site_admin\": false\n" +
                "    }\n" +
                "  }"

        const val PAYLOAD_MILESTONE: String = "{\n" +
                "    \"action\": \"closed\",\n" +
                "    \"issue\": {\n" +
                "      \"url\": \"https://api.github.com/repos/mock/webhook/issues/16\",\n" +
                "      \"repository_url\": \"https://api.github.com/repos/mock/webhook\",\n" +
                "      \"labels_url\": \"https://api.github.com/repos/mock/webhook/issues/16/labels{/name}\",\n" +
                "      \"comments_url\": \"https://api.github.com/repos/mock/webhook/issues/16/comments\",\n" +
                "      \"events_url\": \"https://api.github.com/repos/mock/webhook/issues/16/events\",\n" +
                "      \"html_url\": \"https://github.com/mock/webhook/issues/16\",\n" +
                "      \"id\": 809869512,\n" +
                "      \"node_id\": \"MDU6SXNzdWU4MDk4Njk1MTI=\",\n" +
                "      \"number\": 16,\n" +
                "      \"title\": \"titulo\",\n" +
                "      \"user\": {\n" +
                "        \"login\": \"mock\",\n" +
                "        \"id\": 42354016,\n" +
                "        \"node_id\": \"MDQ6VXNlcjQyMzU0MDE2\",\n" +
                "        \"avatar_url\": \"https://avatars.githubusercontent.com/u/42354016?v=4\",\n" +
                "        \"gravatar_id\": \"\",\n" +
                "        \"url\": \"https://api.github.com/users/mock\",\n" +
                "        \"html_url\": \"https://github.com/mock\",\n" +
                "        \"followers_url\": \"https://api.github.com/users/mock/followers\",\n" +
                "        \"following_url\": \"https://api.github.com/users/mock/following{/other_user}\",\n" +
                "        \"gists_url\": \"https://api.github.com/users/mock/gists{/gist_id}\",\n" +
                "        \"starred_url\": \"https://api.github.com/users/mock/starred{/owner}{/repo}\",\n" +
                "        \"subscriptions_url\": \"https://api.github.com/users/mock/subscriptions\",\n" +
                "        \"organizations_url\": \"https://api.github.com/users/mock/orgs\",\n" +
                "        \"repos_url\": \"https://api.github.com/users/mock/repos\",\n" +
                "        \"events_url\": \"https://api.github.com/users/mock/events{/privacy}\",\n" +
                "        \"received_events_url\": \"https://api.github.com/users/mock/received_events\",\n" +
                "        \"type\": \"User\",\n" +
                "        \"site_admin\": false\n" +
                "      },\n" +
                "      \"labels\": [],\n" +
                "      \"state\": \"closed\",\n" +
                "      \"locked\": false,\n" +
                "      \"assignee\": null,\n" +
                "      \"assignees\": [],\n" +
                "      \"milestone\": {\n" +
                "        \"url\": \"https://api.github.com/repos/mock/webhook/milestones/1\",\n" +
                "        \"html_url\": \"https://github.com/mock/webhook/milestone/1\",\n" +
                "        \"labels_url\": \"https://api.github.com/repos/mock/webhook/milestones/1/labels\",\n" +
                "        \"id\": 6442096,\n" +
                "        \"node_id\": \"MDk6TWlsZXN0b25lNjQ0MjA5Ng==\",\n" +
                "        \"number\": 1,\n" +
                "        \"title\": \"milestone\",\n" +
                "        \"description\": null,\n" +
                "        \"creator\": {\n" +
                "          \"login\": \"mock\",\n" +
                "          \"id\": 42354016,\n" +
                "          \"node_id\": \"MDQ6VXNlcjQyMzU0MDE2\",\n" +
                "          \"avatar_url\": \"https://avatars.githubusercontent.com/u/42354016?v=4\",\n" +
                "          \"gravatar_id\": \"\",\n" +
                "          \"url\": \"https://api.github.com/users/mock\",\n" +
                "          \"html_url\": \"https://github.com/mock\",\n" +
                "          \"followers_url\": \"https://api.github.com/users/mock/followers\",\n" +
                "          \"following_url\": \"https://api.github.com/users/mock/following{/other_user}\",\n" +
                "          \"gists_url\": \"https://api.github.com/users/mock/gists{/gist_id}\",\n" +
                "          \"starred_url\": \"https://api.github.com/users/mock/starred{/owner}{/repo}\",\n" +
                "          \"subscriptions_url\": \"https://api.github.com/users/mock/subscriptions\",\n" +
                "          \"organizations_url\": \"https://api.github.com/users/mock/orgs\",\n" +
                "          \"repos_url\": \"https://api.github.com/users/mock/repos\",\n" +
                "          \"events_url\": \"https://api.github.com/users/mock/events{/privacy}\",\n" +
                "          \"received_events_url\": \"https://api.github.com/users/mock/received_events\",\n" +
                "          \"type\": \"User\",\n" +
                "          \"site_admin\": false\n" +
                "        },\n" +
                "        \"open_issues\": 1,\n" +
                "        \"closed_issues\": 1,\n" +
                "        \"state\": \"open\",\n" +
                "        \"created_at\": \"2021-02-17T05:29:54Z\",\n" +
                "        \"updated_at\": \"2021-02-17T05:38:06Z\",\n" +
                "        \"due_on\": null,\n" +
                "        \"closed_at\": null\n" +
                "      },\n" +
                "      \"comments\": 0,\n" +
                "      \"created_at\": \"2021-02-17T05:33:48Z\",\n" +
                "      \"updated_at\": \"2021-02-17T05:38:06Z\",\n" +
                "      \"closed_at\": \"2021-02-17T05:38:06Z\",\n" +
                "      \"author_association\": \"OWNER\",\n" +
                "      \"active_lock_reason\": null,\n" +
                "      \"body\": \" \",\n" +
                "      \"performed_via_github_app\": null\n" +
                "    },\n" +
                "    \"repository\": {\n" +
                "      \"id\": 321581581,\n" +
                "      \"node_id\": \"MDEwOlJlcG9zaXRvcnkzMjE1ODE1ODE=\",\n" +
                "      \"name\": \"webhook\",\n" +
                "      \"full_name\": \"mock/webhook\",\n" +
                "      \"private\": true,\n" +
                "      \"owner\": {\n" +
                "        \"login\": \"mock\",\n" +
                "        \"id\": 42354016,\n" +
                "        \"node_id\": \"MDQ6VXNlcjQyMzU0MDE2\",\n" +
                "        \"avatar_url\": \"https://avatars.githubusercontent.com/u/42354016?v=4\",\n" +
                "        \"gravatar_id\": \"\",\n" +
                "        \"url\": \"https://api.github.com/users/mock\",\n" +
                "        \"html_url\": \"https://github.com/mock\",\n" +
                "        \"followers_url\": \"https://api.github.com/users/mock/followers\",\n" +
                "        \"following_url\": \"https://api.github.com/users/mock/following{/other_user}\",\n" +
                "        \"gists_url\": \"https://api.github.com/users/mock/gists{/gist_id}\",\n" +
                "        \"starred_url\": \"https://api.github.com/users/mock/starred{/owner}{/repo}\",\n" +
                "        \"subscriptions_url\": \"https://api.github.com/users/mock/subscriptions\",\n" +
                "        \"organizations_url\": \"https://api.github.com/users/mock/orgs\",\n" +
                "        \"repos_url\": \"https://api.github.com/users/mock/repos\",\n" +
                "        \"events_url\": \"https://api.github.com/users/mock/events{/privacy}\",\n" +
                "        \"received_events_url\": \"https://api.github.com/users/mock/received_events\",\n" +
                "        \"type\": \"User\",\n" +
                "        \"site_admin\": false\n" +
                "      },\n" +
                "      \"html_url\": \"https://github.com/mock/webhook\",\n" +
                "      \"description\": null,\n" +
                "      \"fork\": false,\n" +
                "      \"url\": \"https://api.github.com/repos/mock/webhook\",\n" +
                "      \"forks_url\": \"https://api.github.com/repos/mock/webhook/forks\",\n" +
                "      \"keys_url\": \"https://api.github.com/repos/mock/webhook/keys{/key_id}\",\n" +
                "      \"collaborators_url\": \"https://api.github.com/repos/mock/webhook/collaborators{/collaborator}\",\n" +
                "      \"teams_url\": \"https://api.github.com/repos/mock/webhook/teams\",\n" +
                "      \"hooks_url\": \"https://api.github.com/repos/mock/webhook/hooks\",\n" +
                "      \"issue_events_url\": \"https://api.github.com/repos/mock/webhook/issues/events{/number}\",\n" +
                "      \"events_url\": \"https://api.github.com/repos/mock/webhook/events\",\n" +
                "      \"assignees_url\": \"https://api.github.com/repos/mock/webhook/assignees{/user}\",\n" +
                "      \"branches_url\": \"https://api.github.com/repos/mock/webhook/branches{/branch}\",\n" +
                "      \"tags_url\": \"https://api.github.com/repos/mock/webhook/tags\",\n" +
                "      \"blobs_url\": \"https://api.github.com/repos/mock/webhook/git/blobs{/sha}\",\n" +
                "      \"git_tags_url\": \"https://api.github.com/repos/mock/webhook/git/tags{/sha}\",\n" +
                "      \"git_refs_url\": \"https://api.github.com/repos/mock/webhook/git/refs{/sha}\",\n" +
                "      \"trees_url\": \"https://api.github.com/repos/mock/webhook/git/trees{/sha}\",\n" +
                "      \"statuses_url\": \"https://api.github.com/repos/mock/webhook/statuses/{sha}\",\n" +
                "      \"languages_url\": \"https://api.github.com/repos/mock/webhook/languages\",\n" +
                "      \"stargazers_url\": \"https://api.github.com/repos/mock/webhook/stargazers\",\n" +
                "      \"contributors_url\": \"https://api.github.com/repos/mock/webhook/contributors\",\n" +
                "      \"subscribers_url\": \"https://api.github.com/repos/mock/webhook/subscribers\",\n" +
                "      \"subscription_url\": \"https://api.github.com/repos/mock/webhook/subscription\",\n" +
                "      \"commits_url\": \"https://api.github.com/repos/mock/webhook/commits{/sha}\",\n" +
                "      \"git_commits_url\": \"https://api.github.com/repos/mock/webhook/git/commits{/sha}\",\n" +
                "      \"comments_url\": \"https://api.github.com/repos/mock/webhook/comments{/number}\",\n" +
                "      \"issue_comment_url\": \"https://api.github.com/repos/mock/webhook/issues/comments{/number}\",\n" +
                "      \"contents_url\": \"https://api.github.com/repos/mock/webhook/contents/{+path}\",\n" +
                "      \"compare_url\": \"https://api.github.com/repos/mock/webhook/compare/{base}...{head}\",\n" +
                "      \"merges_url\": \"https://api.github.com/repos/mock/webhook/merges\",\n" +
                "      \"archive_url\": \"https://api.github.com/repos/mock/webhook/{archive_format}{/ref}\",\n" +
                "      \"downloads_url\": \"https://api.github.com/repos/mock/webhook/downloads\",\n" +
                "      \"issues_url\": \"https://api.github.com/repos/mock/webhook/issues{/number}\",\n" +
                "      \"pulls_url\": \"https://api.github.com/repos/mock/webhook/pulls{/number}\",\n" +
                "      \"milestones_url\": \"https://api.github.com/repos/mock/webhook/milestones{/number}\",\n" +
                "      \"notifications_url\": \"https://api.github.com/repos/mock/webhook/notifications{?since,all,participating}\",\n" +
                "      \"labels_url\": \"https://api.github.com/repos/mock/webhook/labels{/name}\",\n" +
                "      \"releases_url\": \"https://api.github.com/repos/mock/webhook/releases{/id}\",\n" +
                "      \"deployments_url\": \"https://api.github.com/repos/mock/webhook/deployments\",\n" +
                "      \"created_at\": \"2020-12-15T07:04:36Z\",\n" +
                "      \"updated_at\": \"2020-12-16T22:09:06Z\",\n" +
                "      \"pushed_at\": \"2020-12-16T22:09:04Z\",\n" +
                "      \"git_url\": \"git://github.com/mock/webhook.git\",\n" +
                "      \"ssh_url\": \"git@github.com:mock/webhook.git\",\n" +
                "      \"clone_url\": \"https://github.com/mock/webhook.git\",\n" +
                "      \"svn_url\": \"https://github.com/mock/webhook\",\n" +
                "      \"homepage\": null,\n" +
                "      \"size\": 82,\n" +
                "      \"stargazers_count\": 0,\n" +
                "      \"watchers_count\": 0,\n" +
                "      \"language\": \"Kotlin\",\n" +
                "      \"has_issues\": true,\n" +
                "      \"has_projects\": true,\n" +
                "      \"has_downloads\": true,\n" +
                "      \"has_wiki\": true,\n" +
                "      \"has_pages\": false,\n" +
                "      \"forks_count\": 0,\n" +
                "      \"mirror_url\": null,\n" +
                "      \"archived\": false,\n" +
                "      \"disabled\": false,\n" +
                "      \"open_issues_count\": 1,\n" +
                "      \"license\": null,\n" +
                "      \"forks\": 0,\n" +
                "      \"open_issues\": 1,\n" +
                "      \"watchers\": 0,\n" +
                "      \"default_branch\": \"main\"\n" +
                "    },\n" +
                "    \"sender\": {\n" +
                "      \"login\": \"mock\",\n" +
                "      \"id\": 42354016,\n" +
                "      \"node_id\": \"MDQ6VXNlcjQyMzU0MDE2\",\n" +
                "      \"avatar_url\": \"https://avatars.githubusercontent.com/u/42354016?v=4\",\n" +
                "      \"gravatar_id\": \"\",\n" +
                "      \"url\": \"https://api.github.com/users/mock\",\n" +
                "      \"html_url\": \"https://github.com/mock\",\n" +
                "      \"followers_url\": \"https://api.github.com/users/mock/followers\",\n" +
                "      \"following_url\": \"https://api.github.com/users/mock/following{/other_user}\",\n" +
                "      \"gists_url\": \"https://api.github.com/users/mock/gists{/gist_id}\",\n" +
                "      \"starred_url\": \"https://api.github.com/users/mock/starred{/owner}{/repo}\",\n" +
                "      \"subscriptions_url\": \"https://api.github.com/users/mock/subscriptions\",\n" +
                "      \"organizations_url\": \"https://api.github.com/users/mock/orgs\",\n" +
                "      \"repos_url\": \"https://api.github.com/users/mock/repos\",\n" +
                "      \"events_url\": \"https://api.github.com/users/mock/events{/privacy}\",\n" +
                "      \"received_events_url\": \"https://api.github.com/users/mock/received_events\",\n" +
                "      \"type\": \"User\",\n" +
                "      \"site_admin\": false\n" +
                "    }\n" +
                "  }"

    }
}