CREATE TABLE IF NOT EXISTS LICENSE
(
    LICENSE_ID SERIAL PRIMARY KEY,
    KEY        VARCHAR(50)  NOT NULL,
    NAME       VARCHAR(50)  NOT NULL,
    SPDX_ID    VARCHAR(30)  NOT NULL,
    URL        VARCHAR(255) NOT NULL,
    NODE_ID    VARCHAR(30)  NOT NULL
);