CREATE TABLE IF NOT EXISTS LICENSE
(
    LICENSE_ID SERIAL PRIMARY KEY,
    KEY        VARCHAR(50) UNIQUE NOT NULL,
    NAME       VARCHAR(50)        NOT NULL,
    SPDX_ID    VARCHAR(30) UNIQUE NOT NULL,
    URL        VARCHAR(255)       NOT NULL,
    NODE_ID    VARCHAR(30) UNIQUE NOT NULL
);