CREATE TABLE IF NOT EXISTS SENDER
(
    SENDER_ID           SERIAL PRIMARY KEY,
    LOGIN               VARCHAR(50) UNIQUE NOT NULL,
    NODE_ID             VARCHAR(50) UNIQUE NOT NULL,
    AVATAR_URL          VARCHAR(255)       NOT NULL,
    GRAVATAR_ID         VARCHAR(50)        NOT NULL,
    URL                 VARCHAR(255)       NOT NULL,
    HTML_URL            VARCHAR(255)       NOT NULL,
    FOLLOWERS_URL       VARCHAR(255)       NOT NULL,
    FOLLOWING_URL       VARCHAR(255)       NOT NULL,
    GISTS_URL           VARCHAR(255)       NOT NULL,
    STARRED_URL         VARCHAR(255)       NOT NULL,
    SUBSCRIPTIONS_URL   VARCHAR(255)       NOT NULL,
    ORGANIZATIONS_URL   VARCHAR(255)       NOT NULL,
    REPOS_URL           VARCHAR(255)       NOT NULL,
    EVENTS_URL          VARCHAR(255)       NOT NULL,
    RECEIVED_EVENTS_URL VARCHAR(255)       NOT NULL,
    TYPE                VARCHAR(30)        NOT NULL,
    SITE_ADMIN          BOOLEAN            NOT NULL,
    EVENT_ID            INT                NOT NULL
);