ALTER TABLE
    PAYLOAD
    ADD
        CONSTRAINT C_PAYLOAD_ISSUE FOREIGN KEY (ISSUE_ID) REFERENCES ISSUE (ISSUE_ID);

ALTER TABLE
    PAYLOAD
    ADD
        CONSTRAINT C_PAYLOAD_REPOSITORY FOREIGN KEY (REPOSITORY_ID) REFERENCES REPOSITORY (REPOSITORY_ID);

ALTER TABLE
    PAYLOAD
    ADD
        CONSTRAINT C_PAYLOAD_SENDER FOREIGN KEY (SENDER_ID) REFERENCES SENDER (SENDER_ID);
