ALTER TABLE IF EXISTS ISSUE_RESPONSIBLE
    ADD CONSTRAINT C_ISSUE_RESPONSIBLE_ISSUE
        FOREIGN KEY (ISSUE_ID)
            REFERENCES ISSUE (ISSUE_ID);

ALTER TABLE IF EXISTS ISSUE_RESPONSIBLE
    ADD CONSTRAINT C_ISSUE_RESPONSIBLE_ASSIGNEES
        FOREIGN KEY (ASSIGNEES_ID)
            REFERENCES ASSIGNEES (ASSIGNEES_ID)
