CREATE TABLE IF NOT EXISTS ISSUE
(
    ISSUE_ID                 SERIAL PRIMARY KEY,
    URL                      VARCHAR(255)       NOT NULL,
    REPOSITORY_URL           VARCHAR(255)       NOT NULL,
    LABELS_URL               VARCHAR(255)       NOT NULL,
    COMMENTS_URL             VARCHAR(255)       NOT NULL,
    EVENTS_URL               VARCHAR(255)       NOT NULL,
    HTML_URL                 VARCHAR(255)       NOT NULL,
    NODE_ID                  VARCHAR(50) UNIQUE NOT NULL,
    NUMBER                   INT UNIQUE         NOT NULL,
    TITLE                    VARCHAR(100)       NOT NULL,
    STATE                    VARCHAR(20)        NOT NULL,
    LOCKED                   BOOLEAN            NOT NULL,
    COMMENTS                 VARCHAR(255)       NOT NULL,
    CREATED_AT               DATE               NOT NULL,
    UPDATED_AT               DATE,
    CLOSED_AT                DATE,
    AUTHOR_ASSOCIATION       VARCHAR(20)        NOT NULL,
    ACTIVE_LOCK_REASON       VARCHAR(30),
    BODY                     VARCHAR(2500),
    PERFORMED_VIA_GITHUB_APP VARCHAR(30),
    USER_ID                  INT                NOT NULL,
    ASSIGNEE_ID              INT,
    MILESTONE_ID             INT,
    EVENT_ID                 INT                NOT NULL
);