CREATE TABLE IF NOT EXISTS LABELS
(
    LABELS_ID   SERIAL PRIMARY KEY,
    NODE_ID     VARCHAR(50) NOT NULL,
    URL         VARCHAR(80) NOT NULL,
    NAME        VARCHAR(50) NOT NULL,
    COLOR       VARCHAR(20) NOT NULL,
    "default"   BOOLEAN     NOT NULL,
    DESCRIPTION VARCHAR(80),
    ISSUE_ID    INT         NOT NULL
);