CREATE TABLE IF NOT EXISTS LABEL (
    LABEL_ID INT PRIMARY KEY,
    NODE_ID VARCHAR(50) UNIQUE NOT NULL,
    URL VARCHAR(80) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    COLOR VARCHAR(20) NOT NULL,
    "DEFAULT" BOOLEAN NOT NULL,
    DESCRIPTION VARCHAR(80),
    ISSUE_ID INT NOT NULL
);