CREATE TABLE IF NOT EXISTS MILESTONE (
    URL VARCHAR(80) NOT NULL,
    HTML_URL VARCHAR(80) NOT NULL,
    LABELS_URL VARCHAR(80) NOT NULL,
    MILESTONE_ID INT PRIMARY KEY,
    NODE_ID VARCHAR(50) UNIQUE NOT NULL,
    NUMBER INT NOT NULL,
    TITLE VARCHAR(80) NOT NULL,
    DESCRIPTION VARCHAR(100),
    OPEN_ISSUES INT NOT NULL,
    CLOSED_ISSUES INT NOT NULL,
    STATE VARCHAR(20) NOT NULL,
    CREATED_AT DATE NOT NULL,
    UPDATED_AT DATE,
    DUE_ON DATE,
    CLOSED_AT DATE,
    ISSUE_ID INT UNIQUE NOT NULL
);