CREATE TABLE IF NOT EXISTS MILESTONE
(
    URL           VARCHAR(80) NOT NULL,
    HTML_URL      VARCHAR(80) NOT NULL,
    LABELS_URL    VARCHAR(80) NOT NULL,
    MILESTONE_ID  BIGINT PRIMARY KEY,
    NODE_ID       VARCHAR(50) NOT NULL,
    NUMBER        INT         NOT NULL,
    TITLE         VARCHAR(80) NOT NULL,
    DESCRIPTION   VARCHAR(100),
    OPEN_ISSUES   INT         NOT NULL,
    CLOSED_ISSUES INT         NOT NULL,
    STATE         VARCHAR(20) NOT NULL,
    CREATED_AT    DATE        NOT NULL,
    UPDATED_AT    DATE,
    DUE_ON        DATE,
    CLOSED_AT     DATE,
    CREATOR_ID    INT UNIQUE  NOT NULL
);