CREATE TABLE IF NOT EXISTS REPOSITORY
(
    REPOSITORY_ID     SERIAL PRIMARY KEY,
    NODE_ID           VARCHAR(100) UNIQUE NOT NULL,
    NAME              VARCHAR(100) UNIQUE NOT NULL,
    FULL_NAME         VARCHAR(100)        NOT NULL,
    PRIVATE           BOOLEAN             NOT NULL,
    HTML_URL          VARCHAR(255)        NOT NULL,
    DESCRIPTION       VARCHAR(255),
    FORK              BOOLEAN             NOT NULL,
    URL               VARCHAR(255)        NOT NULL,
    FORKS_URL         VARCHAR(255)        NOT NULL,
    KEYS_URL          VARCHAR(255)        NOT NULL,
    COLLABORATORS_URL VARCHAR(255)        NOT NULL,
    TEAMS_URL         VARCHAR(255)        NOT NULL,
    HOOKS_URL         VARCHAR(255)        NOT NULL,
    ISSUE_EVENTS_URL  VARCHAR(255)        NOT NULL,
    EVENTS_URL        VARCHAR(255)        NOT NULL,
    ASSIGNEES_URL     VARCHAR(255)        NOT NULL,
    BRANCHES_URL      VARCHAR(255)        NOT NULL,
    TAGS_URL          VARCHAR(255)        NOT NULL,
    BLOBS_URL         VARCHAR(255)        NOT NULL,
    GIT_TAGS_URL      VARCHAR(255)        NOT NULL,
    GIT_REFS_URL      VARCHAR(255)        NOT NULL,
    TREES_URL         VARCHAR(255)        NOT NULL,
    STATUSES_URL      VARCHAR(255)        NOT NULL,
    LANGUAGES_URL     VARCHAR(255)        NOT NULL,
    STARGAZERS_URL    VARCHAR(255)        NOT NULL,
    CONTRIBUTORS_URL  VARCHAR(255)        NOT NULL,
    SUBSCRIBERS_URL   VARCHAR(255)        NOT NULL,
    SUBSCRIPTION_URL  VARCHAR(255)        NOT NULL,
    COMMITS_URL       VARCHAR(255)        NOT NULL,
    GIT_COMMITS_URL   VARCHAR(255)        NOT NULL,
    COMMENTS_URL      VARCHAR(255)        NOT NULL,
    ISSUE_COMMENT_URL VARCHAR(255)        NOT NULL,
    CONTENTS_URL      VARCHAR(255)        NOT NULL,
    COMPARE_URL       VARCHAR(255)        NOT NULL,
    MERGES_URL        VARCHAR(255)        NOT NULL,
    ARCHIVE_URL       VARCHAR(255)        NOT NULL,
    DOWNLOADS_URL     VARCHAR(255)        NOT NULL,
    ISSUES_URL        VARCHAR(255)        NOT NULL,
    PULLS_URL         VARCHAR(255)        NOT NULL,
    MILESTONES_URL    VARCHAR(255)        NOT NULL,
    NOTIFICATIONS_URL VARCHAR(255)        NOT NULL,
    LABELS_URL        VARCHAR(255)        NOT NULL,
    RELEASES_URL      VARCHAR(255)        NOT NULL,
    DEPLOYMENTS_URL   VARCHAR(255)        NOT NULL,
    CREATED_AT        TIMESTAMP         NOT NULL,
    UPDATED_AT        TIMESTAMP,
    PUSHED_AT         TIMESTAMP,
    GIT_URL           VARCHAR(255)        NOT NULL,
    SSH_URL           VARCHAR(255)        NOT NULL,
    CLONE_URL         VARCHAR(255)        NOT NULL,
    SVN_URL           VARCHAR(255)        NOT NULL,
    HOMEPAGE          VARCHAR(255),
    SIZE              INT                 NOT NULL,
    STARGAZERS_COUNT  INT                 NOT NULL,
    WATCHERS_COUNT    INT                 NOT NULL,
    LANGUAGE          VARCHAR(255)        NOT NULL,
    HAS_ISSUES        BOOLEAN             NOT NULL,
    HAS_PROJECTS      BOOLEAN             NOT NULL,
    HAS_DOWNLOADS     BOOLEAN             NOT NULL,
    HAS_WIKI          BOOLEAN             NOT NULL,
    HAS_PAGES         BOOLEAN             NOT NULL,
    FORKS_COUNT       INT                 NOT NULL,
    MIRROR_URL        VARCHAR(255),
    ARCHIVED          BOOLEAN             NOT NULL,
    DISABLED          BOOLEAN             NOT NULL,
    OPEN_ISSUES_COUNT INT                 NOT NULL,
    FORKS             INT                 NOT NULL,
    OPEN_ISSUES       INT                 NOT NULL,
    WATCHERS          INT                 NOT NULL,
    DEFAULT_BRANCH    VARCHAR(20)         NOT NULL,
    LICENSE_ID        INT,
    OWNER_ID          INT                 NOT NULL,
    EVENT_ID          INT          NOT NULL
);